#!/usr/bin/env python

import sys
import argparse
import exofop


parser = argparse.ArgumentParser(description="Make a star.ini file for input to"
                                 " VESPA by scraping values from ExoFOP K2")
parser.add_argument('epic', help='EPIC ID of target star', type=int)
parser.add_argument('-o', '--outfile', help='save to outfile',
    type=str, default='star.ini')
args = parser.parse_args()


with open(args.outfile, 'w') as f:
    s1 = exofop.get_phot(args.epic, verbose=False, return_str=True)
    f.write(s1)
    s2 = exofop.get_stellar(args.epic, verbose=False, return_str=True)
    f.write(s2)
