#!/usr/bin/env python

import sys
import argparse
import exofop


parser = argparse.ArgumentParser(description="Make a star.ini file for input to"
                                 " VESPA by scraping values from ExoFOP K2")
parser.add_argument('epic', help='EPIC ID of target star', type=int)
args = parser.parse_args()


exofop.get_phot(args.epic, verbose=True)
exofop.get_stellar(args.epic, verbose=True)
